on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: [self-hosted]
     
    steps:
      - name: 01. org secrets
        run: |
          echo "ORG_SECRETS=${{ secrets.ORG_SECRETS }}" >> $GITHUB_ENV
          echo "${{ env.ORG_SECRETS }} "
          
          cat > org_secrets <<EOF
          ORG_SECRETS=$env.ORG_SECRETS
          EOF

          cat ./org_secrets
          
